const MAX_WORLD_SIZE = 65536;
const MAX_WORLD_DEPTH = 128;

const WORLD_SIZE_BYTES = 2;
const WORLD_DEPTH_BYTES = 1;

const WorldLimit = {
    MAX_SIZE: MAX_WORLD_SIZE,
    MAX_WIDTH: MAX_WORLD_SIZE,
    MAX_HEIGHT: MAX_WORLD_SIZE,
    MAX_DEPTH: MAX_WORLD_DEPTH,

    SIZE_BYTES: WORLD_SIZE_BYTES,
    WIDTH_BYTES: WORLD_SIZE_BYTES,
    HEIGHT_BYTES: WORLD_SIZE_BYTES,
    DEPTH_BYTES: WORLD_DEPTH_BYTES
}

export default WorldLimit;
